> /root/Code/Code/dataset.py(38)__getitem__()
-> if radii[c] <= ANCHOR_SIZES[0] / 2:
*** AttributeError: 'list' object has no attribute 'shape'
(3,)
(3,)
> /root/Code/Code/dataset.py(49)__getitem__()
-> target[tuple(place)] = vector
(26, 8, 14, 0)
[1, -0.75, -0.75, -0.5, 3.255854428517024]
Traceback (most recent call last):
  File "train.py", line 213, in <module>
    train(args)
  File "train.py", line 99, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/Code/Code/dataset.py", line 49, in __getitem__
    #         target[tuple(place)] = vector
  File "/root/Code/Code/dataset.py", line 49, in __getitem__
    #         target[tuple(place)] = vector
  File "/root/miniconda3/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/root/miniconda3/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit